### ISSUE TITLE
what does mergedInto used for 

### ISSUE THREAD

**Issue by zzz6519003** [IvanVergiliev/2048-react#2]
:beer:

**Comment by IvanVergiliev** [comment]
Hey, sorry for the slow reply - did you figure it out yourself?

mergedInto is used when two tiles get merged into one - say, if you move two 4s to get an 8. Then both of the 4s will be mergedInto a new tile with value 8. This helps determine the right behaviour when animating the movements.

**Comment by zzz6519003** [comment]
yes  handsome ivan!
